# -*- coding: utf-8 -*-

"""
Description: Scrapy spider- and downloader-middleware stubs for the
    PoliticalPoller project, generated by `scrapy startproject` and left
    at their default no-op behavior. Neither class is currently wired up
    in settings.py's SPIDER_MIDDLEWARES/DOWNLOADER_MIDDLEWARES, so they
    have no effect on a crawl as-is; they're kept here as the place to add
    cross-cutting request/response handling (retry logic, custom headers,
    response filtering, etc.) if a future spider needs it, without having
    to re-scaffold a middleware from scratch.
LLM: claude-sonnet-5
"""

from scrapy import signals


class PoliticalpollerSpiderMiddleware(object):
    """Not all methods need to be defined. If a method is not defined,
    Scrapy acts as if the spider middleware does not modify the passed
    objects."""

    """
    Description: Scrapy calls this to construct the middleware instance,
        wiring its spider_opened() method up to the spider_opened signal.
    Param[in] crawler:  The Crawler this middleware is being created for
    Param[out] s:        A new instance of this middleware
    Owner: @opnanalysis
    """
    @classmethod
    def from_crawler(cls, crawler):
        s = cls()
        crawler.signals.connect(s.spider_opened, signal=signals.spider_opened)
        return s

    """
    Description: Called for each response that goes through this spider
        middleware and into the spider. Should return None or raise an
        exception.
    Param[in] response:  The Response about to reach the spider
    Param[in] spider:    The Spider the response is headed to
    Owner: @opnanalysis
    """
    def process_spider_input(self, response, spider):
        return None

    """
    Description: Called with the results returned from the Spider, after
        it has processed a response. Must return (or yield) an iterable
        of Request, dict, or Item objects.
    Param[in] response:  The Response that produced these results
    Param[in] result:    Iterable of Request/dict/Item objects the spider
        callback returned/yielded
    Param[in] spider:    The Spider that produced the results
    Owner: @opnanalysis
    """
    def process_spider_output(self, response, result, spider):
        for i in result:
            yield i

    """
    Description: Called when a spider or process_spider_input() method
        (from another spider middleware) raises an exception. Should
        return either None or an iterable of Request, dict, or Item
        objects.
    Param[in] response:   The Response being processed when the
        exception was raised
    Param[in] exception:  The exception raised
    Param[in] spider:     The Spider that was processing the response
    Owner: @opnanalysis
    """
    def process_spider_exception(self, response, exception, spider):
        pass

    """
    Description: Called with the spider's start requests, working like
        process_spider_output() except there's no associated response.
        Must return only Request objects (not items).
    Param[in] start_requests:  Iterable of the spider's initial Requests
    Param[in] spider:          The Spider the requests belong to
    Owner: @opnanalysis
    """
    def process_start_requests(self, start_requests, spider):
        for r in start_requests:
            yield r

    """
    Description: Signal handler connected to spider_opened (via
        from_crawler()); logs that the spider has started.
    Param[in] spider:  The Spider that just opened
    Owner: @opnanalysis
    """
    def spider_opened(self, spider):
        spider.logger.info('Spider opened: %s' % spider.name)


class PoliticalpollerDownloaderMiddleware(object):
    """Not all methods need to be defined. If a method is not defined,
    Scrapy acts as if the downloader middleware does not modify the
    passed objects."""

    """
    Description: Scrapy calls this to construct the middleware instance,
        wiring its spider_opened() method up to the spider_opened signal.
    Param[in] crawler:  The Crawler this middleware is being created for
    Param[out] s:        A new instance of this middleware
    Owner: @opnanalysis
    """
    @classmethod
    def from_crawler(cls, crawler):
        s = cls()
        crawler.signals.connect(s.spider_opened, signal=signals.spider_opened)
        return s

    """
    Description: Called for each request that goes through this
        downloader middleware. Must either return None (continue
        processing this request), return a Response, return a Request,
        or raise IgnoreRequest.
    Param[in] request:  The Request about to be downloaded
    Param[in] spider:   The Spider that issued the request
    Owner: @opnanalysis
    """
    def process_request(self, request, spider):
        return None

    """
    Description: Called with the Response returned from the downloader.
        Must either return a Response, return a Request, or raise
        IgnoreRequest.
    Param[in] request:   The original Request
    Param[in] response:  The Response the downloader produced
    Param[in] spider:    The Spider the response is headed to
    Owner: @opnanalysis
    """
    def process_response(self, request, response, spider):
        return response

    """
    Description: Called when a download handler or a process_request()
        (from another downloader middleware) raises an exception. Must
        either return None (continue the exception chain), a Response
        (stops the chain), or a Request (stops the chain).
    Param[in] request:    The Request being processed when the exception
        was raised
    Param[in] exception:  The exception raised
    Param[in] spider:     The Spider that issued the request
    Owner: @opnanalysis
    """
    def process_exception(self, request, exception, spider):
        pass

    """
    Description: Signal handler connected to spider_opened (via
        from_crawler()); logs that the spider has started.
    Param[in] spider:  The Spider that just opened
    Owner: @opnanalysis
    """
    def spider_opened(self, spider):
        spider.logger.info('Spider opened: %s' % spider.name)
